### ISSUE TITLE
Can't read rcon password

### ISSUE THREAD

**Issue by watar** [maca134/MBCon#1]
Trying to set up to evaluate your software but get a msg saying:

==========================
MBCon - by maca134
maca134@googlemail.com
==========================

Config file found, continuing to load...
Unloading MBCon
ERROR: Error Loading Settings: Error reading BEServer.cfg: Could not find rcon password in BEServer.cfg.
--------------------------------------
Then it exits, The BEPAth is set and are correct. BEServer.cfg is present at given location and works fine with BEC etc.

**Comment by maca134** [comment]
Please triple check the path is right and the format of the cfg file is right

**Comment by watar** [comment]
config.ini:
; Path to BE folder (were all the BE filters live)
BEPath=C:\Servers\arma3_public\..tfr\BattlEye

and that is where the BEserver.cfg is located.
Content of beserver.cfg: 
Rconpassword XXXXXX

Works fine in BEC and all other rcon tools.

**Comment by watar** [comment]
Not sure why github reformats my BEpath.
Correct should be BEPath = C:\ Servers \ arma3_public \ ..tfr \BattlEye
without the extra spaces

**Comment by maca134** [comment]
Try changing the password field to
RConPassword

If that solves ur issue i will push a change.

**Comment by watar** [comment]
Yes, that worked
