### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by stargatefreak** [maca134/MBCon#5]
Fresh install of 0.0.0.2, changed the ip address to local. unable to connect.
# 

MBCon - by maca134
# maca134@googlemail.com

Config file found, continuing to load...
Loading BEClient...
Loading Plugins...
Plugin BEFilterMonitor loading failed: BEFilterMonitor has been disabled
Plugin Logger loading failed: Logger has been disabled
Plugin PlayerCheck loading failed: PlayerCheck has been disabled
Plugin ScheduledTasks loading failed: ScheduledTasks has been disabled
Plugin SimpleMessages loading failed: SimpleMessages has been disabled
Plugin WebLogger loading failed: WebLogger has been disabled
Plugin WebRcon loading failed: WebRcon has been disabled
Connecting to server...
Sending Message: Server will restart in 1 hour, 59 minutes.
Sending Message: Server will restart in 1 hour, 59 minutes.
Sending Message: Server will restart in 1 hour, 59 minutes.
Sending Message: Server will restart in 1 hour, 59 minutes.
Sending Message: Server will restart in 1 hour, 59 minutes.
Connection to 127.0.0.1:2302 failed: Invalid login details!
Failed to connect to server. Attempt 1/5
Connection to 127.0.0.1:2302 failed: Invalid login details!
Failed to connect to server. Attempt 2/5
Connection to 127.0.0.1:2302 failed: Invalid login details!
Failed to connect to server. Attempt 3/5
Connection to 127.0.0.1:2302 failed: Invalid login details!
Failed to connect to server. Attempt 4/5
Connection to 127.0.0.1:2302 failed: Invalid login details!
Failed to connect to server. Attempt 5/5
Unloading MBCon
Unloading Plugins
Unloading Console
Unloading RestartMessages
BE Disconnected

**Comment by stargatefreak** [comment]
; This is the general config for the app.
; EACH PLUGIN HAS ITS OWN "config.ini" THAT NEED SETTING UP INDIVIDUALLY

[General]
; Server connection details
IP=127.0.0.1
Port=2302

; Path to BE folder (were all the BE filters live)
BEPath=D:\ozzygamingservices\armahc\battleye

; If not set the plugin folder will be within the app root
PluginPath=D:\ozzygamingservices\armahc\mbcon\plugins

[Admins]
; Define admins as guid = level

; some guy
7b313c3a4a8f13fa07f8f91427dd6674 = 100

**Comment by stargatefreak** [comment]
sorry about this issue. I found there were 2 beserver.cfg file. deleted the second and it now works.

**Comment by tinboye** [comment]
I am trying to get this to work, im using beserver_x64, so not sure if this works with that?

i am getting the exact same issue as above
