### ISSUE TITLE
Instruction Ambiguity

### ISSUE THREAD

**Issue by jimburnsphd** [maca134/MBCon#9]
The beauty of language is that it can be clear and concise, removing all question and ambiguity.  The config.ini states,

[Admins]
; Define admins as guid = level
7b313c3a4a8f13fa07f8f91427dd6674 = 100

Yet in no way does it explain WTF this GUID comes from.  It's NOT a Steam ID... it's NOT an ARMA Player ID, WTF is it?  

How simple it might have been just to be clear.

Thanks.

**Comment by maca134** [comment]
if your not happy with something make a push request! and try to be a little less rude next time!

**Comment by jimburnsphd** [comment]
Thanks.  And you try and pull your head out of your idiotic ass. The rudeness started with your ineptness.  Thanks.
